# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelbuddy', '0002_auto_20161021_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='end_date',
            field=models.DateTimeField(verbose_name=['%m/%d/%Y']),
        ),
        migrations.AlterField(
            model_name='trips',
            name='start_date',
            field=models.DateTimeField(verbose_name=['%m/%d/%Y']),
        ),
    ]
