# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 02:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelbuddy', '0004_auto_20161021_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelbuddy.Users')),
            ],
        ),
        migrations.RemoveField(
            model_name='trips',
            name='participant',
        ),
        migrations.AddField(
            model_name='groups',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelbuddy.Trips'),
        ),
    ]
